{
	"template":"Double Base Layer (HTML Edition)",
	"version":"6.9.2_b1,953 (2018-02-23 1508)",
	"boundingBox":"3555828.453 6210653.830499999 3973196.327 6554743.4995",
	"layers":[
	{
		"type":"base-layer",
		"id":"_UKR_adm2.shp1",
		"name":"Borders",
		"geometry":"polygon",
		"url":"_UKR_adm2.shp1.js",
		"visible":true,
		"symbolSize":15,
		"fillColor":"#ffffff",
		"fillOpacity":0.8,
		"borderColor":"#7f7e7e",
		"borderThickness":1.2,
		"showLabels":false,
		"minLabelExtent":0,
		"maxLabelExtent":1000000,
		"iconPath":"",
		"showDataTips":true,
		"showInLayerList":true
	},
	{
		"type":"base-layer",
		"id":"_HCF_ua.shp2",
		"name":"Hospitals",
		"geometry":"point",
		"url":"_HCF_ua.shp2.js",
		"visible":true,
		"symbolSize":8.5,
		"fillColor":"#ffffff",
		"fillOpacity":0.8,
		"borderColor":"#7f7f7f",
		"borderThickness":1,
		"showLabels":false,
		"minLabelExtent":0,
		"maxLabelExtent":1000000,
		"iconPath":"",
		"showDataTips":true,
		"showInLayerList":true
	},
	{
		"type":"ags-layer",
		"id":"wms-527047110",
		"name":"World Topographic Map",
		"geometry":"image",
		"visible":true,
		"url":"http://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/export?",
		"layers":"0",
		"srs":"102100",
		"params":"&format=PNG32&bgcolor=0xffffff&transparent=FALSE",
		"tile":true,
		"showInLayerList":true
	}
	]
}